# Base configs
baseurl: "wwww.google.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Japan Tokyo"
subtitle: "See the world through my eyes!"
author: "Surakan Jiwchan"
header:
 title: "Japan Tokyo"
 subtitle: "by Surakan Jiwchan"
footer:
 name: "Hey there, my name is Surakan or Bom "
 bio: "I like Japan country."
 github: "Nice to meet you">fork me on github</a> ;)"
web_design: "SJ"
social_urls:
  facebook: "https://www.facebook.com/"
  twitter: "https://www.twitter.com/"
  instagram: "https://www.instagram.com/"
  dribbble: "https://dribbble.com/"
  linkedin: "https://in.linkedin.com/in/"
  github: "https://www.github.com/"
